name: acnerase2
description: Acne-trigger ingredient scanner using TFLite and camera
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.1
  google_mlkit_text_recognition: ^0.15.0
  image_picker: ^1.1.0
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/1.tflite
    - assets/dairy_acne_trigger_ingredients.json
    - assets/gluten_acne_trigger_ingredients.json
